
PERSON_STATUS_HOME = 'Home'
PERSON_STATUS_JUST_ARRIVED = 'Just Arrived'
PERSON_STATUS_ARRIVING = 'Arriving'
PERSON_STATUS_JUST_LEFT = 'Just Left'
PERSON_STATUS_AWAY = 'Away'
PERSON_STATUS_EXTENDED_AWAY = 'Extended Away'

HOME_PERSON_STATUSES = [PERSON_STATUS_HOME, PERSON_STATUS_JUST_ARRIVED]

PRESENCE_MODE_EVERYONE_IS_HOME = 'Everyone is Home'
PRESENCE_MODE_SOMEONE_IS_HOME = 'Someone is Home'
PRESENCE_MODE_NO_ONE_IS_HOME = 'No One is Home'
PRESENCE_MODE_SOMEONE_IS_ARRIVING_HOME = 'Someone is Arriving Home'
